# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170115_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlist',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='bucketlist',
            old_name='modified',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='bucketlistitem',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='bucketlistitem',
            old_name='modified',
            new_name='date_modified',
        ),
    ]
